twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_4_layout.html.twig']
    globals:
        website_title: '%env(WEBSITE_TITLE)%'
        avatar_repo: '/assets/media/avatar'