twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_4_layout.html.twig']
    globals:
        website_title: '%env(WEBSITE_TITLE)%'
        assets_version: '%env(ASSETS_VERSION)%'
        avatar_repo: '/assets/media/avatar'
        book_repo: '/assets/media/books/book'